services:
    mock-server:
        image: ${PROJECT_NAME}:latest
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: development
            HUSKY: 0
            SERVER_PORT: ${SERVER_PORT}
            MOCK_LLM_RESPONSE_TYPE: ${MOCK_LLM_RESPONSE_TYPE}
            MAX_LOREM_PARAS: ${MAX_LOREM_PARAS}
            LLM_URL_ENDPOINT: ${LLM_URL_ENDPOINT}
            DEBUG: ${DEBUG}
            LLM_NAME: ${LLM_NAME}
            VALIDATE_REQUESTS: ${VALIDATE_REQUESTS}
            LOG_REQUESTS: ${LOG_REQUESTS}
        ports:
            - 8000:8000
